#!/usr/bin/env python3
"""
Manifold PR — LaTeX Table Generation
=====================================

This script generates publication-ready LaTeX and CSV tables summarizing
participation ratio (PR) results from the manifold dimensionality analysis,
comparing experts and novices across 22 bilateral cortical regions.

METHODS (Academic Manuscript Section)
--------------------------------------
Summary tables were generated to present participation ratio (PR) values—a
measure of effective dimensionality in neural representations—across expertise
groups and brain regions. For each of the 22 regions of interest (ROIs) from
the Glasser multimodal parcellation, we report:

1. **Group mean PR with 95% confidence intervals**: Separate columns for expert
   and novice groups, computed using parametric bootstrap (scipy.stats).

2. **Group difference (ΔPR)**: Computed as (Expert mean - Novice mean) with 95%
   confidence interval derived from the t-distribution.

3. **Statistical significance**: Results from Welch's two-sample t-test
   (scipy.stats.ttest_ind with equal_var=False) comparing expert and novice PR
   values. P-values are corrected for multiple comparisons using the
   Benjamini-Hochberg false discovery rate (FDR) procedure (α=0.05).

4. **Effect size**: Cohen's d, calculated as the difference in means divided by
   the pooled standard deviation, quantifying the magnitude of expertise
   differences.

The LaTeX table uses multicolumn headers to organize statistics by expertise
group and includes significance markers (* p<0.05, ** p<0.01, *** p<0.001 FDR-
corrected) to highlight regions showing reliable differences.

Inputs
------
- pr_results.pkl: Dictionary containing (from 01_manifold_analysis.py):
  - 'summary_stats': DataFrame with per-ROI, per-group PR descriptives (mean, CI, SEM)
  - 'stats_results': DataFrame with Welch t-test results, FDR q-values, and Cohen's d
  - 'roi_info': DataFrame with ROI metadata (names, hemisphere, anatomical grouping)
  - 'roi_labels': List of ROI IDs in analysis order

Outputs
-------
- tables/manifold_pr_results.tex: LaTeX table with multicolumn headers
- tables/manifold_pr_results.csv: CSV version for reference

Dependencies
------------
- modules.tables.generate_pr_results_table: Table formatting for PR analysis
- common.logging_utils: Logging setup
- common.io_utils: Results directory finder

Usage
-----
python chess-manifold/81_table_manifold_pr.py

Analysis 2 from manuscript: Supplementary Table, Methods Sec 3.6
"""

import os
import sys
from pathlib import Path

# Ensure repo root is on sys.path for 'common' imports
_cur = os.path.dirname(__file__)
for _up in (os.path.join(_cur, '..'), os.path.join(_cur, '..', '..')):
    _cand = os.path.abspath(_up)
    if os.path.isdir(os.path.join(_cand, 'common')) and _cand not in sys.path:
        sys.path.insert(0, _cand)
        break
import pickle
from common import setup_script, log_script_end
from modules.tables import generate_pr_results_table

# ============================================================================
# Configuration & Setup
# ============================================================================

# Locate the latest manifold analysis results directory
# This script reads from the most recent timestamped results folder
results_dir, logger, dirs = setup_script(
    __file__,
    results_pattern='manifold',
    output_subdirs=['tables'],
    log_name='tables_manifold.log',
)
RESULTS_DIR = results_dir
tables_dir = dirs['tables']

# ============================================================================
# Load PR Results
# ============================================================================

logger.info("Loading PR results from pickle file...")

# Load the pr_results.pkl file generated by 01_manifold_analysis.py
# This file contains all PR values, summary statistics, and test results
with open(RESULTS_DIR / 'pr_results.pkl', 'rb') as f:
    res = pickle.load(f)

# Extract components needed for table generation
summary_stats = res['summary_stats']  # DataFrame: per-ROI, per-group PR descriptives (mean, CI, SEM)
stats_results = res['stats_results']  # DataFrame: Welch t-tests, FDR q-values, Cohen's d
roi_info = res['roi_info']  # DataFrame: ROI metadata (names, hemisphere, group)

logger.info(f"Loaded results for {len(stats_results)} ROIs")

# ============================================================================
# Generate LaTeX and CSV Tables
# ============================================================================

logger.info("Generating LaTeX and CSV tables...")

# Use manifold-specific table generator to format PR results
# This function:
# 1. Merges summary statistics with statistical test results
# 2. Formats means with 95% CIs: "mean (CI_low, CI_high)"
# 3. Formats ΔPR (expert - novice) with 95% CIs
# 4. Adds FDR-corrected significance markers (*, **, ***)
# 5. Orders ROIs by anatomical grouping and hemisphere
# 6. Creates multicolumn headers separating expert and novice columns
tex_path, csv_path = generate_pr_results_table(
    summary_stats=summary_stats,  # Per-group descriptives (mean, CI)
    stats_results=stats_results,  # Statistical test results (t, p, q_fdr, Cohen's d)
    roi_info=roi_info,  # ROI metadata for pretty names
    output_dir=tables_dir,  # Output directory for tables
    use_fdr=True,  # Use FDR-corrected p-values (q-values) for significance markers
    filename_tex='manifold_pr_results.tex',  # LaTeX output filename
    filename_csv='manifold_pr_results.csv',  # CSV output filename
)

# ============================================================================
# Finish
# ============================================================================

log_script_end(logger)
logger.info(f"Saved PR results LaTeX: {tex_path}")
logger.info(f"Saved PR results CSV: {csv_path}")
